global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Recording rules for ML metrics
rule_files:
  - "ml_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Inference API
  - job_name: 'ml-inference-api'
    static_configs:
      - targets: ['ml-api:5000', 'localhost:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # MLflow Server
  - job_name: 'mlflow-server'
    static_configs:
      - targets: ['mlflow-server:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics (if node_exporter is available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Database metrics (if postgres_exporter is available)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/prometheus/metrics'
    scrape_interval: 30s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093