name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Verify installation
      run: |
        python --version
        pip --version
        python -c "import sklearn, pandas, numpy, flask; print('All major dependencies imported successfully')"
        python -c "import mlflow; print('MLflow available')" || echo "MLflow not available (expected in CI)"
        python -c "import prometheus_client; print('Prometheus client available')" || echo "Prometheus client not available (expected in CI)"
    
    - name: Lint with flake8
      run: |
        pip install flake8
        echo "Running flake8 syntax checks..."
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=mlruns,__pycache__,.git
        echo "Running flake8 style checks (warnings only)..."
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=mlruns,__pycache__,.git
    
    - name: Train model for testing
      run: |
        python train_model.py
    
    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=app --cov=train_model --cov-report=xml --cov-report=html
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true
    
    - name: Upload coverage reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports-${{ matrix.python-version }}
        path: |
          ./coverage.xml
          ./htmlcov/
        retention-days: 30
      if: always()

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit security scan
      run: |
        echo "Running Bandit security scan..."
        bandit -r . -x tests/ -f json -o bandit-report.json || echo "Bandit found some issues (non-critical)"
        echo "Bandit summary:"
        bandit -r . -x tests/ || echo "Security scan completed with warnings"
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: bandit-report.json
        retention-days: 30
      if: always()
    
    - name: Check dependencies for vulnerabilities
      run: |
        echo "Checking dependencies for vulnerabilities..."
        safety check --json --output safety-report.json || echo "Safety found some issues (non-critical)"
        echo "Safety summary:"
        safety check || echo "Dependency scan completed with warnings"
    
    - name: Upload safety report
      uses: actions/upload-artifact@v3
      with:
        name: safety-report
        path: safety-report.json
        retention-days: 30
      if: always()

  build:
    needs: [test, security]
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Train model for container
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python train_model.py
    
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure kubectl
      run: |
        # Configure kubectl for staging environment
        echo "Deploying to staging environment"
        # Add your kubectl configuration here
    
    - name: Deploy to staging
      run: |
        # Update image in deployment
        sed -i "s|ml-inference-service:latest|${{ needs.build.outputs.image-tag }}|g" k8s/deployment.yaml
        echo "Would deploy to staging with image: ${{ needs.build.outputs.image-tag }}"
        # kubectl apply -f k8s/ -n staging

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure kubectl
      run: |
        # Configure kubectl for production environment
        echo "Deploying to production environment"
        # Add your kubectl configuration here
    
    - name: Deploy to production
      run: |
        # Update image in deployment
        sed -i "s|ml-inference-service:latest|${{ needs.build.outputs.image-tag }}|g" k8s/deployment.yaml
        echo "Would deploy to production with image: ${{ needs.build.outputs.image-tag }}"
        # kubectl apply -f k8s/ -n production
    
    - name: Run smoke tests
      run: |
        echo "Running post-deployment smoke tests"
        # Add smoke tests here

  performance-test:
    needs: deploy-staging
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install requests locust
    
    - name: Run performance tests
      run: |
        echo "Running performance tests against staging"
        # Add performance test commands here
        # python demo.py  # If demo.py is configured for staging